import {
  Layout,
  LayoutDashboard,
  FolderKanban,
  LayoutTemplate,
  Wrench,
  Users,
  Code2,
  Shield,
  Download,
  Image as ImageIcon,
  Video as VideoIcon,
  FileText,
  Building,
  Box,
  FileCode,
  Database,
  Server,
  Terminal,
  Cpu,
  Monitor,
  ShoppingBag,
  BarChart3,
  Layers,
  Component,
  FunctionSquare,
  FileJson,
  Globe,
  Settings,
  Puzzle
} from 'lucide-react';
import { MenuItem, Tenant, Department, Developer, Role, Permission, Resource } from './types';

export const LOCALE = {
  zh: {
    login: '登录',
    username: '用户名',
    password: '密码',
    welcome: '欢迎回来',
    loginDesc: '登录星云低代码管理平台',
    dashboard: '工作台',
    projects: '项目管理',
    templates: '项目模板',
    resources: '开发资源',
    organizations: '组织管理',
    departments: '部门管理',
    developers: '开发者管理',
    roles: '权限角色',
    downloads: '资源下载',
    imageEditor: 'AI 图片编辑',
    videoGenerator: 'Veo 视频生成',
    theme: '主题',
    language: '语言',
    tenant: '帐套',
    logout: '退出登录',
    quickStart: '快速上手',
    tutorialVideos: '教学视频',
    documentation: '平台文档',
    systemStatus: '系统状态',
    recentActivity: '最近动态',
    uploadImage: '上传图片',
    generate: '生成',
    promptPlaceholder: '描述您想要进行的修改...',
    videoPromptPlaceholder: '描述视频内容 (可选)...',
    loading: '处理中...',
    selectKey: '选择 API Key',
    apiKeyRequired: '需要 API Key 才能继续',
    billingInfo: '需要使用付费项目的 API Key。',
    veoDescription: '上传图片并生成 16:9 或 9:16 的视频。',
    editorDescription: '使用文字指令编辑图片内容。',
    recentProjects: '最近项目',
    createProject: '创建项目',
    importProject: '导入项目',
    exportProject: '导出',
    viewKey: '密钥',
    projectKey: '项目密钥',
    copyKey: '复制密钥',
    openProjectDir: '本地项目',
    codeRepository: '代码仓库',
    gitConfig: '仓库配置',
    gitConnect: '连接仓库',
    gitBranch: '分支',
    gitCommit: '提交代码',
    gitPush: '推送',
    gitPull: '拉取',
    gitMessagePlaceholder: '输入提交信息 (Commit Message)...',
    gitChanges: '变更文件',
    gitHistory: '提交历史',
    gitStaged: '暂存区',
    gitUnstaged: '工作区',
    gitDiff: '差异对比',
    gitNoChanges: '暂无变更',
    gitRepoUrl: '仓库地址 (HTTPS/SSH)',
    gitConnectSuccess: '仓库连接成功',
    gitAuthor: '作者',
    gitDate: '日期',
    gitHash: 'Hash',
    gitPullFile: '拉取文件',
    gitRevert: '回滚',
    gitMsg: '提交信息',
    close: '关闭',
    closeOthers: '关闭其他',
    closeAll: '关闭所有',
    closeRight: '关闭右侧标签页',
    closeLeft: '关闭左侧标签页',
    publishTemplate: '发布模板',
    confirmPublish: '确认发布',
    publishTemplateConfirm: '确定要把这个项目发布为项目模板吗？',
    publishSuccess: '模板发布成功',
    userManual: '使用手册',
    trainingVideos: '培训视频',
    quickActions: '快速开始',
    viewAll: '查看全部',
    lastEdited: '最后编辑',
    status: '状态',
    helpCenter: '帮助中心',
    videoDuration: '时长',
    newcomerGuide: '新人向导',
    newcomerGuideDesc: '全方位平台入门指南',
    searchProjects: '搜索项目...',
    noProjectsFound: '未找到匹配的项目',
    pushToGithub: '推送到 GitHub',
    syncing: '同步中...',
    synced: '已同步',
    productManual: '产品使用手册',
    productBlog: '产品功能博客',
    save: '保存',
    cancel: '取消',
    // Project Management
    totalProjects: '项目总数',
    activeProjects: '进行中',
    completedProjects: '已关闭',
    viewGrid: '网格视图',
    viewList: '列表视图',
    members: '成员',
    owner: '负责人',
    actions: '操作',
    edit: '编辑',
    copy: '复制',
    copyConfirm: '确定要复制这个项目吗？',
    delete: '删除',
    deleteConfirm: '确定要删除这个项目吗？',
    filterAll: '全部',
    statusInProgress: '进行中',
    statusClosed: '关闭',
    projectNumber: '项目编号',
    projectNumberPlaceholder: '请输入项目编号 (例如: P-2024-001)',
    // Template Management
    templateGallery: '公共模板库',
    myTemplates: '我的模板',
    createTemplate: '新建模板',
    editTemplate: '编辑模板',
    searchTemplates: '搜索模板...',
    useTemplate: '使用此模板',
    previewTemplate: '预览',
    templateCategory: '分类',
    templateAuthor: '作者',
    templateUsage: '使用次数',
    noTemplatesFound: '未找到匹配的模板',
    confirmDeleteTemplate: '确定要删除这个模板吗？',
    catEnterprise: '企业管理',
    catECommerce: '电商零售',
    catGeneral: '通用基础',
    catData: '数据分析',
    templateName: '模板名称',
    templateDesc: '模板描述',
    templateTags: '标签',
    templateTagsPlaceholder: '输入标签，用逗号分隔',
    // Organization Management
    orgName: '组织名称',
    orgCode: '组织编码',
    orgOwner: '拥有者',
    orgStatus: '状态',
    orgCreated: '创建时间',
    createOrg: '创建组织',
    editOrg: '编辑组织',
    deleteOrg: '删除组织',
    confirmDeleteOrg: '确定要删除该组织吗？这将移除该组织下的所有数据。',
    searchOrgs: '搜索组织...',
    noOrgsFound: '未找到匹配的组织',
    enterOrgName: '请输入组织名称',
    enterOrgCode: '请输入组织编码',
    // Department Management
    deptName: '部门名称',
    deptCode: '部门编码',
    deptManager: '负责人',
    deptMembers: '成员数',
    deptStatus: '状态',
    deptDesc: '描述',
    parentDepartment: '上级部门',
    rootDepartment: '根节点 (无上级)',
    createDepartment: '新建部门',
    editDepartment: '编辑部门',
    deleteDepartment: '删除部门',
    deptStatusActive: '启用',
    deptStatusInactive: '停用',
    deptCreatedSuccess: '部门创建成功',
    deptUpdatedSuccess: '部门更新成功',
    deptDeletedSuccess: '部门删除成功',
    confirmDeleteDept: '确定要删除该部门吗？',
    managerPlaceholder: '请选择负责人',
    searchDepartments: '搜索部门...',
    noDepartmentsFound: '未找到匹配的部门',
    enterDeptName: '请输入部门名称',
    enterDeptCode: '请输入部门编码',
    // Developer Management
    devName: '姓名',
    devPhone: '手机号码',
    devEmail: '邮箱',
    devPosition: '职务',
    devRole: '角色',
    devDept: '所属部门',
    devGender: '性别',
    devAvatar: '头像',
    devBirthday: '生日',
    devStatus: '状态',
    devRemarks: '备注',
    createDeveloper: '添加开发者',
    editDeveloper: '编辑开发者',
    deleteDeveloper: '删除开发者',
    confirmDeleteDev: '确定要删除该开发者吗？',
    male: '男',
    female: '女',
    searchDevelopers: '搜索开发者...',
    noDevelopersFound: '未找到匹配的开发者',
    enterDevName: '请输入姓名',
    enterDevPhone: '请输入手机号码',
    enterDevEmail: '请输入邮箱',
    enterDevPosition: '请输入职务',
    selectDevRole: '选择角色',
    selectDevDept: '选择部门',
    selectDevGender: '选择性别',
    selectDevStatus: '选择状态',
    selectAvatar: '选择头像',
    devJoined: '入职日期',
    // Role Management
    roleName: '角色名称',
    roleCode: '角色编码',
    roleDesc: '描述',
    roleStatus: '状态',
    roleUsers: '关联用户数',
    rolePermissions: '权限配置',
    createRole: '新建角色',
    editRole: '编辑角色',
    deleteRole: '删除角色',
    confirmDeleteRole: '确定要删除该角色吗？此操作将影响关联用户的权限。',
    searchRoles: '搜索角色...',
    noRolesFound: '未找到匹配的角色',
    enterRoleName: '请输入角色名称',
    enterRoleCode: '请输入角色编码',
    permModule: '模块',
    permActions: '操作权限',
    perm_projects_view: '查看项目',
    perm_projects_create: '创建项目',
    perm_projects_edit: '编辑项目',
    perm_projects_delete: '删除项目',
    perm_projects_import: '导入项目',
    perm_projects_export: '导出项目',
    perm_projects_copy: '复制项目',
    perm_projects_view_key: '查看密钥',
    perm_projects_publish: '发布模板',
    perm_projects_push_git: '推送Git',
    perm_templates_view: '查看模板',
    perm_templates_edit: '编辑模板',
    perm_templates_delete: '删除模板',
    perm_templates_use: '使用模板',
    perm_resources_view: '查看资源',
    perm_resources_create: '创建资源',
    perm_resources_edit: '编辑资源',
    perm_resources_delete: '删除资源',
    perm_resources_manage_groups: '管理分组',
    perm_orgs_view: '查看组织',
    perm_orgs_create: '创建组织',
    perm_orgs_edit: '编辑组织',
    perm_orgs_delete: '删除组织',
    perm_depts_view: '查看部门',
    perm_depts_create: '创建部门',
    perm_depts_edit: '编辑部门',
    perm_depts_delete: '删除部门',
    perm_devs_view: '查看开发者',
    perm_devs_create: '创建开发者',
    perm_devs_edit: '编辑开发者',
    perm_devs_delete: '删除开发者',
    perm_roles_view: '查看角色',
    perm_roles_create: '创建角色',
    perm_roles_edit: '编辑角色',
    perm_roles_delete: '删除角色',
    perm_downloads_view: '查看下载',
    selectAllPerms: '全选',
    deselectAllPerms: '取消全选',
    // Resource Management (New)
    resPageTemplate: '页面模板',
    resBizComponent: '业务组件',
    resVueComponent: 'VUE组件',
    resProComponent: '专业组件',
    resFunction: '函数',
    resScript: '脚本',
    resService: '后端服务',
    resApi: '系统接口',
    resSql: 'SQL脚本',
    resName: '资源名称',
    resCode: '资源编码',
    resGroup: '分组类别',
    resPreview: '预览图片',
    resDesc: '描述',
    resAuthor: '作者',
    resUpdated: '更新时间',
    createResource: '新建资源',
    editResource: '编辑资源',
    deleteResource: '删除资源',
    searchResources: '搜索资源...',
    noResourcesFound: '暂无相关资源',
    confirmDeleteRes: '确定要删除该资源吗？此操作不可恢复。',
    enterResName: '请输入资源名称',
    enterResCode: '请输入资源编码',
    enterResGroup: '请输入分组 (例如: 财务, 通用)',
    enterResPreview: '请输入图片 URL',
    selectResType: '选择资源类型',
    resManageGroups: '分组管理',
    resGroupMgmtTitle: '资源分组管理',
    resGroupPlaceholder: '输入新分组名称',
    resGroupCount: '资源数量',
    confirmDeleteGroup: '确定删除该分组吗？该分组下的资源将被移动到 "General"。',
    resAppType: '应用类型',
    appTypeWeb: 'Web端',
    appTypeApp: '移动端',
    appTypeBackend: '后端',
    uploadPreview: '点击或拖拽上传图片',
    uploadPreviewHint: '支持 PNG, JPG, WEBP',
    richTextPlaceholder: '在此输入详细描述...',
    // Downloads
    downloadsTitle: '开发资源下载',
    downloadsDesc: '获取最新的引擎安装包、开发文档和集成模板。',
    winEngine: 'Window版本服务引擎',
    winEngineDesc: '适用于 Windows 环境的本地服务引擎安装包。',
    linuxEngine: 'Linux版本服务引擎',
    linuxEngineDesc: '适用于 Linux 服务器环境的服务引擎安装包。',
    installGuide: '服务引擎安装指南',
    installGuideDesc: '详细的服务引擎部署与配置文档。',
    jeecgTemplate: 'JeeCG集成模板',
    jeecgTemplateDesc: 'JeeCG 低代码平台集成开发模板。',
    downloadBtn: '下载',
    openLinkBtn: '打开链接',
    copyPwd: '复制密码',
    pwdCopied: '密码已复制',
    accessPwd: '访问密码',
    // Wizard Translations
    step1: '基础信息',
    step2: '模板选择',
    step3: '数据库配置',
    step4: '确认信息',
    createProjectTitle: '新建项目',
    createProjectSubtitle: '请按照引导步骤设置您的新项目，您可以在任意步骤返回修改',
    projectName: '项目名称',
    projectDesc: '项目描述',
    projectPath: '项目保存路径',
    projectType: '项目类型',
    typeWeb: 'Web应用',
    typeMobile: '移动应用',
    typeDesktop: '桌面应用',
    next: '下一步',
    prev: '上一步',
    create: '立即创建',
    selectTemplate: '选择应用模板',
    selectTemplateTitle: 'Select Project Template',
    selectTemplateDesc: '选择一个模板可以快速开始您的项目，模板包含了预置的组件和布局。',
    dbType: '数据库类型',
    dbConnection: '连接字符串',
    confirmTitle: '请确认项目信息',
    successCreated: '项目创建成功！',
    emptyTemplate: '空白应用',
    crmTemplate: '基础模板',
    erpTemplate: '高级模板',
    cmsTemplate: 'MES项目',
    // Database Configuration
    dbConfigTitle: '数据库连接配置',
    dbConfigDesc: '选择项目使用的数据库类型，并配置连接信息。',
    dbHost: '数据库主机',
    dbPort: '数据库端口',
    dbName: '数据库名称',
    dbUser: '用户名',
    dbPassword: '密码',
    dbTestConnection: '创建后测试数据库连接',
    dbNamePlaceholder: '请输入数据库名称',
    dbUserPlaceholder: '请输入数据库用户名',
    dbPasswordPlaceholder: '请输入数据库密码',
    // Template Descriptions
    emptyTemplateDesc: '从头开始创建项目，完全自定义。',
    crmTemplateDesc: '包含基础用户体系、权限管理和后台布局，适合快速构建管理系统。',
    erpTemplateDesc: '集成复杂的工作流引擎和多级审批流程，适合企业级业务管理。',
    cmsTemplateDesc: '完整的工业制造执行系统，包含生产计划、质检、库存等核心模块。',
    namePlaceholder: '请输入项目名称',
    descPlaceholder: '请输入项目描述...',
    pathPlaceholder: '/projects/',
    // Edit Modal
    editProjectTitle: '编辑项目',
    editProjectSubtitle: '修改项目基本信息、状态及成员配置',
    saveChanges: '保存修改',
    saving: '保存中...',
    projectMembers: '项目成员',
    selectMembers: '选择成员',
    loadingMembers: '加载成员列表中...',
    manageMembers: '管理成员',
    // Password Change
    changePassword: '修改密码',
    oldPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认新密码',
    oldPasswordPlaceholder: '请输入当前密码',
    newPasswordPlaceholder: '请输入新密码 (至少6位)',
    confirmPasswordPlaceholder: '请再次输入新密码',
    passwordMismatch: '两次输入的密码不一致',
    passwordSuccess: '密码修改成功，请妥善保管',
    passwordError: '原密码错误，请重试',
    passwordRequirement: '密码长度建议至少6位，包含字母和数字',
    // About Us
    aboutUs: '关于我们',
    productName: '星云',
    productVersion: '产品版本',
    serviceValidUntil: '服务有效期',
    licenseValidUntil: '使用有效期',
    standardEdition: '标准版',
    copyright: '©2021-2024 上海云座信息科技有限公司版权所有',
    // Delete Wizard
    deleteProjectTitle: '删除项目',
    deleteProjectSubtitle: '此操作不可逆，请仔细确认要删除的内容',
    warningTitle: '警告：删除操作不可撤销',
    warningDesc: '删除项目将永久移除相关资源，请谨慎操作。建议在删除前备份重要数据。',
    confirmDelProject: 'Confirm Project to Delete',
    confirmDelDesc: 'Please review the project information below.',
    delStep1: 'Confirm Project',
    delStep2: '选择删除项',
    delStep3: '最终确认',
    delStep4: '删除进度',
    projectID: '项目ID',
    createTime: '创建时间',
    lastModified: '最后修改',
    projectSize: '项目大小',
    associatedResources: '重要提示：删除此项目将同时删除以下关联资源：',
    resFrontend: '项目所有前端页面和组件',
    resBackend: '后端API接口和数据服务',
    resDb: '项目数据库及所有数据',
    resLogs: '项目部署配置和日志',
    resPerms: '项目团队成员权限设置',
    typeToConfirm: '请输入项目名称以确认删除',
    deleting: '正在删除项目资源...',
    deleteSuccess: '项目删除成功',
    resourcePages: '前端资源 (Pages/Components)',
    resourceAPI: '后端资源 (APIs/Services)',
    resourceDB: '数据库 (Tables/Data)',
    resourceAssets: '静态资源 (Images/Videos)',
    // Delete Step 2
    delSelectComponentsTitle: '选择要删除的组件',
    delSelectComponentsDesc: '您可以选择删除项目的特定部分，或删除整个项目。',
    selectAllComponents: '全选所有组件',
    selectedComponentsCount: '已选择 {count} / 4 个组件',
    compFrontend: '前端页面与组件',
    compFrontendDesc: 'All project frontend pages, page layouts, and UI components',
    compBackend: '后端接口与服务',
    compBackendDesc: 'API interfaces, business logic, data services, and middleware',
    compDB: 'Database & Data',
    compDBDesc: 'Project database, tables, stored procedures, and all data',
    compConfig: '配置与部署',
    compConfigDesc: 'Project configuration, env vars, deployment settings, and log files',
    statPages: '页面',
    statComponents: '组件',
    statApis: 'API接口',
    statServices: '服务',
    statTables: '数据表',
    statRecords: '数据记录',
    statEnvs: '环境',
    statFiles: '配置文件',
    dangerZone: '危险操作区域',
    deleteBackups: '同时删除项目备份文件 (3个备份，总计 512 MB)',
    deleteLogs: '同时删除所有操作日志和审计记录',
    dangerActionWarning: 'These actions cannot be undone, please choose carefully',
    // Delete Step 3
    delFinalConfirmTitle: 'Final Confirmation',
    delFinalConfirmSubtitle: 'Please review the deletion summary and enter the project name to confirm.',
    delSummaryTitle: 'Deletion Summary',
    delSummaryProjectName: '项目名称',
    delSummaryFrontend: 'Frontend Pages & Components:',
    delSummaryBackend: 'Backend Interfaces & Services:',
    delSummaryDatabase: 'Database & Data:',
    delSummaryConfig: 'Configuration & Deployment:',
    delSummaryBackups: 'Project Backups:',
    delSummaryLogs: 'Operation Logs:',
    delSummarySpace: 'Est. Freed Space:',
    delStatusDelete: 'Delete',
    delStatusKeep: 'Keep',
    delFrontendDetails: '(24个页面, 156个组件)',
    delBackendDetails: '(42个API接口, 8个服务)',
    delDbDetails: '(18个数据表, 12,458条记录)',
    delConfigDetails: '(6个环境, 45个配置文件)',
    delFinalWarningTitle: '最终确认',
    delFinalWarningDesc: '为了确认您理解此操作的后果，请输入项目名称 "{name}" 以继续。',
    delInputLabel: '输入项目名称',
    delInputPlaceholder: '请输入项目名称',
    delCheckboxLabel: '我理解此操作不可撤销，并确认要删除上述所有选中的组件',
    // Explorer
    expWeb: 'Web端',
    expApp: 'App端',
    expBackend: '后端服务',
    expDatabase: '数据库',
    expExternal: '外部接口',
    expLocalProject: '本地项目',
    expCodeRepo: '代码仓库',
    explorerTitle: '项目资源管理',
    searchFiles: '搜索文件...',
  },
  en: {
    login: 'Login',
    username: 'Username',
    password: 'Password',
    welcome: 'Welcome Back',
    loginDesc: 'Sign in to Nebula LowCode Admin',
    dashboard: 'Workbench',
    projects: 'Projects',
    templates: 'Templates',
    resources: 'Dev Resources',
    organizations: 'Organizations',
    departments: 'Departments',
    developers: 'Developers',
    roles: 'Roles & Perms',
    downloads: 'Downloads',
    imageEditor: 'AI Image Editor',
    videoGenerator: 'Veo Video Gen',
    theme: 'Theme',
    language: 'Language',
    tenant: 'Tenant',
    logout: 'Logout',
    quickStart: 'Quick Start',
    tutorialVideos: 'Tutorial Videos',
    documentation: 'Documentation',
    systemStatus: 'System Status',
    recentActivity: 'Recent Activity',
    uploadImage: 'Upload Image',
    generate: 'Generate',
    promptPlaceholder: 'Describe the changes you want...',
    videoPromptPlaceholder: 'Describe the video content (optional)...',
    loading: 'Processing...',
    selectKey: 'Select API Key',
    apiKeyRequired: 'API Key Required',
    billingInfo: 'A paid project API Key is required.',
    veoDescription: 'Upload an image to generate a 16:9 or 9:16 video.',
    editorDescription: 'Edit images using natural language prompts.',
    recentProjects: 'Recent Projects',
    createProject: 'Create Project',
    importProject: 'Import Project',
    exportProject: 'Export',
    viewKey: 'Key',
    projectKey: 'Project Key',
    copyKey: 'Copy Key',
    openProjectDir: 'Local Project',
    codeRepository: 'Code Repository',
    gitConfig: 'Repo Config',
    gitConnect: 'Connect Repo',
    gitBranch: 'Branch',
    gitCommit: 'Commit Code',
    gitPush: 'Push',
    gitPull: 'Pull',
    gitMessagePlaceholder: 'Enter commit message...',
    gitChanges: 'Changes',
    gitHistory: 'History',
    gitStaged: 'Staged Changes',
    gitUnstaged: 'Working Changes',
    gitDiff: 'Diff',
    gitNoChanges: 'No Changes',
    gitRepoUrl: 'Repository URL (HTTPS/SSH)',
    gitConnectSuccess: 'Repository connected successfully',
    gitAuthor: 'Author',
    gitDate: 'Date',
    gitHash: 'Hash',
    gitPullFile: 'Pull File',
    gitRevert: 'Revert',
    gitMsg: 'Commit Message',
    close: 'Close',
    closeOthers: 'Close Others',
    closeAll: 'Close All',
    closeRight: 'Close to the Right',
    closeLeft: 'Close to the Left',
    publishTemplate: 'Publish as Template',
    confirmPublish: 'Confirm Publish',
    publishTemplateConfirm: 'Are you sure you want to publish this project as a template?',
    publishSuccess: 'Template Published Successfully',
    userManual: 'User Manual',
    trainingVideos: 'Training Videos',
    quickActions: 'Quick Start',
    viewAll: 'View All',
    lastEdited: 'Last Edited',
    status: 'Status',
    helpCenter: 'Help Center',
    videoDuration: 'Duration',
    newcomerGuide: 'Newcomer Guide',
    newcomerGuideDesc: 'Comprehensive platform guide',
    searchProjects: 'Search projects...',
    noProjectsFound: 'No matching projects found',
    pushToGithub: 'Push to GitHub',
    syncing: 'Syncing...',
    synced: 'Synced',
    productManual: 'Product User Manual',
    productBlog: 'Product Features Blog',
    save: 'Save',
    cancel: 'Cancel',
    // Project Management
    totalProjects: 'Total Projects',
    activeProjects: 'In Progress',
    completedProjects: 'Closed',
    viewGrid: 'Grid View',
    viewList: 'List View',
    members: 'Members',
    owner: 'Owner',
    actions: 'Actions',
    edit: 'Edit',
    copy: 'Copy',
    copyConfirm: 'Are you sure you want to copy this project?',
    delete: 'Delete',
    deleteConfirm: 'Are you sure you want to delete this project?',
    filterAll: 'All',
    statusInProgress: 'In Progress',
    statusClosed: 'Closed',
    projectNumber: 'Project Number',
    projectNumberPlaceholder: 'Enter project number (e.g., P-2024-001)',
    // Template Management
    templateGallery: 'Public Gallery',
    myTemplates: 'My Templates',
    createTemplate: 'New Template',
    editTemplate: 'Edit Template',
    searchTemplates: 'Search templates...',
    useTemplate: 'Use Template',
    previewTemplate: 'Preview',
    templateCategory: 'Category',
    templateAuthor: 'Author',
    templateUsage: 'Usage',
    noTemplatesFound: 'No templates found',
    confirmDeleteTemplate: 'Are you sure you want to delete this template?',
    catEnterprise: 'Enterprise',
    catECommerce: 'E-Commerce',
    catGeneral: 'General',
    catData: 'Data & Analytics',
    templateName: 'Template Name',
    templateDesc: 'Description',
    templateTags: 'Tags',
    templateTagsPlaceholder: 'Comma separated tags',
    // Organization Management
    orgName: 'Organization Name',
    orgCode: 'Org Code',
    orgOwner: 'Owner',
    orgStatus: 'Status',
    orgCreated: 'Created At',
    createOrg: 'Create Organization',
    editOrg: 'Edit Organization',
    deleteOrg: 'Delete Organization',
    confirmDeleteOrg: 'Are you sure you want to delete this organization? All data will be removed.',
    searchOrgs: 'Search organizations...',
    noOrgsFound: 'No organizations found',
    enterOrgName: 'Enter organization name',
    enterOrgCode: 'Enter organization code',
    // Department Management
    deptName: 'Department Name',
    deptCode: 'Dept Code',
    deptManager: 'Manager',
    deptMembers: 'Members',
    deptStatus: 'Status',
    deptDesc: 'Description',
    parentDepartment: 'Parent Department',
    rootDepartment: 'Root (No Parent)',
    createDepartment: 'Create Department',
    editDepartment: 'Edit Department',
    deleteDepartment: 'Delete Department',
    deptStatusActive: 'Active',
    deptStatusInactive: 'Inactive',
    deptCreatedSuccess: 'Department created successfully',
    deptUpdatedSuccess: 'Department updated successfully',
    deptDeletedSuccess: 'Department deleted successfully',
    confirmDeleteDept: 'Are you sure you want to delete this department?',
    managerPlaceholder: 'Select Manager',
    searchDepartments: 'Search departments...',
    noDepartmentsFound: 'No departments found',
    enterDeptName: 'Enter department name',
    enterDeptCode: 'Enter department code',
    // Developer Management
    devName: 'Name',
    devPhone: 'Mobile Phone',
    devEmail: 'Email',
    devPosition: 'Position',
    devRole: 'Role',
    devDept: 'Department',
    devGender: 'Gender',
    devAvatar: 'Avatar',
    devBirthday: 'Birthday',
    devStatus: 'Status',
    devRemarks: 'Remarks',
    createDeveloper: 'Add Developer',
    editDeveloper: 'Edit Developer',
    deleteDeveloper: 'Delete Developer',
    confirmDeleteDev: 'Are you sure you want to delete this developer?',
    male: 'Male',
    female: 'Female',
    searchDevelopers: 'Search developers...',
    noDevelopersFound: 'No developers found',
    enterDevName: 'Enter name',
    enterDevPhone: 'Enter mobile number',
    enterDevEmail: 'Enter email',
    enterDevPosition: 'Enter position',
    selectDevRole: 'Select Role',
    selectDevDept: 'Select Department',
    selectDevGender: 'Select Gender',
    selectDevStatus: 'Select Status',
    selectAvatar: 'Select Avatar',
    devJoined: 'Joined Date',
    // Role Management
    roleName: 'Role Name',
    roleCode: 'Role Code',
    roleDesc: 'Description',
    roleStatus: 'Status',
    roleUsers: 'Users',
    rolePermissions: 'Permissions',
    createRole: 'Create Role',
    editRole: 'Edit Role',
    deleteRole: 'Delete Role',
    confirmDeleteRole: 'Are you sure? This will affect permissions for assigned users.',
    searchRoles: 'Search roles...',
    noRolesFound: 'No roles found',
    enterRoleName: 'Enter role name',
    enterRoleCode: 'Enter role code',
    permModule: 'Module',
    permActions: 'Actions',
    perm_projects_view: 'View Projects',
    perm_projects_create: 'Create Projects',
    perm_projects_edit: 'Edit Projects',
    perm_projects_delete: 'Delete Projects',
    perm_projects_import: 'Import Projects',
    perm_projects_export: 'Export Projects',
    perm_projects_copy: 'Copy Projects',
    perm_projects_view_key: 'View Key',
    perm_projects_publish: 'Publish Template',
    perm_projects_push_git: 'Push to Git',
    perm_templates_view: 'View Templates',
    perm_templates_edit: 'Edit Templates',
    perm_templates_delete: 'Delete Templates',
    perm_templates_use: 'Use Templates',
    perm_resources_view: 'View Resources',
    perm_resources_create: 'Create Resources',
    perm_resources_edit: 'Edit Resources',
    perm_resources_delete: 'Delete Resources',
    perm_resources_manage_groups: 'Manage Groups',
    perm_orgs_view: 'View Organizations',
    perm_orgs_create: 'Create Organizations',
    perm_orgs_edit: 'Edit Organizations',
    perm_orgs_delete: 'Delete Organizations',
    perm_depts_view: 'View Departments',
    perm_depts_create: 'Create Departments',
    perm_depts_edit: 'Edit Departments',
    perm_depts_delete: 'Delete Departments',
    perm_devs_view: 'View Developers',
    perm_devs_create: 'Create Developers',
    perm_devs_edit: 'Edit Developers',
    perm_devs_delete: 'Delete Developers',
    perm_roles_view: 'View Roles',
    perm_roles_create: 'Create Roles',
    perm_roles_edit: 'Edit Roles',
    perm_roles_delete: 'Delete Roles',
    perm_downloads_view: 'View Downloads',
    selectAllPerms: 'Select All',
    deselectAllPerms: 'Deselect All',
    // Resource Management (New)
    resPageTemplate: 'Page Template',
    resBizComponent: 'Business Component',
    resVueComponent: 'Vue Component',
    resProComponent: 'Pro Component',
    resFunction: 'Function',
    resScript: 'Script',
    resService: 'Backend Service',
    resApi: 'System API',
    resSql: 'SQL Script',
    resName: 'Resource Name',
    resCode: 'Resource Code',
    resGroup: 'Category',
    resPreview: 'Preview Image',
    resDesc: 'Description',
    resAuthor: 'Author',
    resUpdated: 'Updated At',
    createResource: 'Create Resource',
    editResource: 'Edit Resource',
    deleteResource: 'Delete Resource',
    searchResources: 'Search resources...',
    noResourcesFound: 'No resources found',
    confirmDeleteRes: 'Are you sure you want to delete this resource? This action cannot be undone.',
    enterResName: 'Enter resource name',
    enterResCode: 'Enter resource code',
    enterResGroup: 'Enter category (e.g. Finance, General)',
    enterResPreview: 'Enter image URL',
    selectResType: 'Select Resource Type',
    resManageGroups: 'Manage Groups',
    resGroupMgmtTitle: 'Resource Group Management',
    resGroupPlaceholder: 'Enter new group name',
    resGroupCount: 'Resource Count',
    confirmDeleteGroup: 'Delete this group? Resources will be moved to "General".',
    resAppType: 'App Type',
    appTypeWeb: 'Web',
    appTypeApp: 'Mobile App',
    appTypeBackend: 'Backend',
    uploadPreview: 'Click or Drag to Upload',
    uploadPreviewHint: 'Supports PNG, JPG, WEBP',
    richTextPlaceholder: 'Enter detailed description here...',
    // Downloads
    downloadsTitle: 'Resource Downloads',
    downloadsDesc: 'Get the latest service engines, documentation, and integration templates.',
    winEngine: 'Windows Service Engine',

    winEngineDesc: 'Local service engine installer for Windows environments.',
    linuxEngine: 'Linux Service Engine',
    linuxEngineDesc: 'Service engine installer for Linux server environments.',
    installGuide: 'Installation Guide',
    installGuideDesc: 'Comprehensive guide for deployment and configuration.',
    jeecgTemplate: 'JeeCG Integration Template',
    jeecgTemplateDesc: 'Development template for JeeCG low-code platform integration.',
    downloadBtn: 'Download',
    openLinkBtn: 'Open Link',
    copyPwd: 'Copy Pwd',
    pwdCopied: 'Copied',
    accessPwd: 'Access Password',
    // Wizard Translations
    step1: 'Basic Info',
    step2: 'Template Selection',
    step3: 'DB Config',
    step4: 'Confirmation',
    createProjectTitle: 'Create New Project',
    createProjectSubtitle: 'Follow the steps to setup your new project. You can go back to modify at any step.',
    projectName: 'Project Name',
    projectDesc: 'Description',
    projectPath: 'Save Path',
    projectType: 'Project Type',
    typeWeb: 'Web App',
    typeMobile: 'Mobile App',
    typeDesktop: 'Desktop App',
    next: 'Next',
    prev: 'Previous',
    create: 'Create Now',
    selectTemplate: 'Select App Template',
    selectTemplateTitle: 'Select Project Template',
    selectTemplateDesc: 'Select a template to kickstart your project with pre-built components and layouts.',
    dbType: 'Database Type',
    dbConnection: 'Connection String',
    confirmTitle: 'Confirm Project Details',
    successCreated: 'Project Created Successfully!',
    emptyTemplate: 'Blank App',
    crmTemplate: 'Basic Template',
    erpTemplate: 'Advanced Template',
    cmsTemplate: 'MES Project',
    // Database Configuration
    dbConfigTitle: 'Database Connection',
    dbConfigDesc: 'Select the database type and configure connection details.',
    dbHost: 'Database Host',
    dbPort: 'Database Port',
    dbName: 'Database Name',
    dbUser: 'Username',
    dbPassword: 'Password',
    dbTestConnection: 'Test connection after creation',
    dbNamePlaceholder: 'Enter database name',
    dbUserPlaceholder: 'Enter username',
    dbPasswordPlaceholder: 'Enter password',
    // Template Descriptions
    emptyTemplateDesc: 'Start from scratch with a completely custom project.',
    crmTemplateDesc: 'Includes basic user system, permissions, and admin layout.',
    erpTemplateDesc: 'Includes workflow engine, approval processes, and reporting.',
    cmsTemplateDesc: 'Manufacturing Execution System with production planning and QA.',
    namePlaceholder: 'Enter project name',
    descPlaceholder: 'Enter description...',
    pathPlaceholder: '/projects/',
    // Edit Modal
    editProjectTitle: 'Edit Project',
    editProjectSubtitle: 'Modify project details, status, and member configuration.',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    projectMembers: 'Project Members',
    selectMembers: 'Select Members',
    loadingMembers: 'Loading members...',
    manageMembers: 'Manage Members',
    // Password Change
    changePassword: 'Change Password',
    oldPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    oldPasswordPlaceholder: 'Enter current password',
    newPasswordPlaceholder: 'Enter new password (min 6 chars)',
    confirmPasswordPlaceholder: 'Confirm your new password',
    passwordMismatch: 'Passwords do not match',
    passwordSuccess: 'Password updated successfully',
    passwordError: 'Current password incorrect, please try again',
    passwordRequirement: 'Password should be at least 6 characters with letters and numbers',
    // About Us
    aboutUs: 'About Us',
    productName: 'Nebula',
    productVersion: 'Product Version',
    serviceValidUntil: 'Service Valid Until',
    licenseValidUntil: 'License Valid Until',
    standardEdition: 'Standard Edition',
    copyright: '©2021-2024 上海云座信息科技有限公司版权所有',
    // Delete Wizard
    deleteProjectTitle: 'Delete Project',
    deleteProjectSubtitle: 'This action is irreversible, please carefully confirm.',
    warningTitle: 'Warning: Action Cannot Be Undone',
    warningDesc: 'Deleting this project will permanently remove associated resources. Please proceed with caution.',
    confirmDelProject: 'Confirm Project to Delete',
    confirmDelDesc: 'Please review the project information below.',
    delStep1: 'Confirm Project',
    delStep2: 'Select Items',
    delStep3: 'Final Confirm',
    delStep4: 'Progress',
    projectID: 'Project ID',
    createTime: 'Created Time',
    lastModified: 'Last Modified',
    projectSize: 'Size',
    associatedResources: 'Important: Deleting this project will also delete:',
    resFrontend: 'All frontend pages and components',
    resBackend: 'Backend APIs and data services',
    resDb: 'Project database and data',
    resLogs: 'Deployment configs and logs',
    resPerms: 'Team member permissions',
    typeToConfirm: 'Type project name to confirm delete',
    deleting: 'Deleting project resources...',
    deleteSuccess: 'Project Deleted Successfully',
    resourcePages: 'Frontend Resources (Pages/Components)',
    resourceAPI: 'Backend Resources (APIs/Services)',
    resourceDB: 'Database (Tables/Data)',
    resourceAssets: 'Static Assets (Images/Videos)',
    // Delete Step 2
    delSelectComponentsTitle: 'Select Components to Delete',
    delSelectComponentsDesc: 'You can choose to delete specific parts of the project, or delete the entire project.',
    selectAllComponents: 'Select All Components',
    selectedComponentsCount: 'Selected {count} / 4 components',
    compFrontend: 'Frontend Pages & Components',
    compFrontendDesc: 'All project frontend pages, page layouts, and UI components',
    compBackend: 'Backend Interfaces & Services',
    compBackendDesc: 'API interfaces, business logic, data services, and middleware',
    compDB: 'Database & Data',
    compDBDesc: 'Project database, tables, stored procedures, and all data',
    compConfig: 'Configuration & Deployment',
    compConfigDesc: 'Project configuration, env vars, deployment settings, and log files',
    statPages: 'Pages',
    statComponents: 'Components',
    statApis: 'APIs',
    statServices: 'Services',
    statTables: 'Tables',
    statRecords: 'Records',
    statEnvs: 'Envs',
    statFiles: 'Configs',
    dangerZone: 'Danger Zone',
    deleteBackups: 'Also delete project backup files (3 backups, 512 MB total)',
    deleteLogs: 'Also delete all operation logs and audit records',
    dangerActionWarning: 'These actions cannot be undone, please choose carefully',
    // Delete Step 3
    delFinalConfirmTitle: 'Final Confirmation',
    delFinalConfirmSubtitle: 'Please review the deletion summary and enter the project name to confirm.',
    delSummaryTitle: 'Deletion Summary',
    delSummaryProjectName: 'Project Name',
    delSummaryFrontend: 'Frontend Pages & Components:',
    delSummaryBackend: 'Backend Interfaces & Services:',
    delSummaryDatabase: 'Database & Data:',
    delSummaryConfig: 'Configuration & Deployment:',
    delSummaryBackups: 'Project Backups:',
    delSummaryLogs: 'Operation Logs:',
    delSummarySpace: 'Est. Freed Space:',
    delStatusDelete: 'Delete',
    delStatusKeep: 'Keep',
    delFrontendDetails: '(24 Pages, 156 Components)',
    delBackendDetails: '(42 APIs, 8 Services)',
    delDbDetails: '(18 Tables, 12,458 Records)',
    delConfigDetails: '(6 Envs, 45 Config Files)',
    delFinalWarningTitle: 'Final Confirmation',
    delFinalWarningDesc: 'To confirm you understand the consequences, please enter project name "{name}" to continue.',
    delInputLabel: 'Enter Project Name',
    delInputPlaceholder: 'Enter project name',
    delCheckboxLabel: 'I understand this action is irreversible and confirm to delete all selected components.',
    // Explorer
    expWeb: 'Web Pages',
    expApp: 'App',
    expBackend: 'Backend',
    expDatabase: 'Database',
    expExternal: 'External APIs',
    expLocalProject: 'Local Project',
    expCodeRepo: 'Right Repository',
    explorerTitle: 'Project Explorer',
    searchFiles: 'Search files...',
  }
};

export const MOCK_PROJECTS = [
  { id: 1, name: 'HR Management System', number: 'P-2023-001', desc: 'Internal HR system for employee management and payroll.', status: 'In Progress', lastEdited: '2 hours ago', color: 'bg-blue-500', size: '128 MB' },
];
