export const texts = {
    zh: {
        save: '保存',
        send: '发送',
        info: '基础信息',
        path: 'Path 参数',
        params: 'Query 参数',
        body: '请求体',
        headers: 'Headers',
        cookies: 'Cookies',
        auth: '鉴权',
        hooks: 'Hook 调用',
        pre: '前置 Hook',
        post: '后置 Hook',
        responseTransform: '响应处理',
        outputPreview: '输出预览',
        key: '参数名',
        type: '类型',
        required: '必填',
        example: '示例值',
        desc: '说明',
        addParam: '添加参数',
        batchEdit: '批量编辑',
        saving: '保存中...',
        systemUrl: '系统地址',
        customUrl: '自定义地址',
        inheritSys: '继承系统配置',
        sysDefault: '使用系统的默认配置',
        enableHook: '启用 Hook',
        javaClass: 'Java 类',
        method: '方法',
        argsConfig: '参数配置',
        importSuccess: '导入成功',
        basicName: '接口名称',
        basicTags: '接口标签',
        basicDesc: '接口说明',
        basicUsage: '详细文档 (Markdown)',
        dragFile: '点击或拖拽上传文件',
        authType: '鉴权类型',
        inheritOp: '继承系统',
        customOp: '自定义',
        none: '无',
        commaMode: '逗号模式',
        colonMode: '冒号模式',
        batchFormatComma: '格式: 参数名,类型,必需,示例值,说明',
        batchFormatColon: '格式: 参数名: 示例值 (其他字段默认)',
        cancel: '取消',
        confirm: '确定',
        visualMode: '可视化模式',
        codeMode: '代码模式',
        sourcePath: '映射路径',
        mockValue: 'Mock',
        addStatus: '添加状态码',
        rootNode: '根节点',
        addChild: '添加子节点',
        method: '请求方法',
        apiPath: '接口路径',
        sendRequest: '发送请求',
        genJwt: '生成 JWT',
        oauth2Flow: '授权流程',
    },
    en: {
        save: 'Save',
        send: 'Send',
        info: 'Basic Info',
        path: 'Path Params',
        params: 'Query Params',
        body: 'Body',
        headers: 'Headers',
        cookies: 'Cookies',
        auth: 'Auth',
        hooks: 'Hooks',
        pre: 'Pre-Hook',
        post: 'Post-Hook',
        responseTransform: 'Response',
        outputPreview: 'Preview',
        key: 'Key',
        type: 'Type',
        required: 'Required',
        example: 'Example',
        desc: 'Description',
        addParam: 'Add Param',
        batchEdit: 'Batch Edit',
        saving: 'Saving...',
        systemUrl: 'System URL',
        customUrl: 'Custom URL',
        inheritSys: 'Inherit System',
        sysDefault: 'Use system defaults',
        enableHook: 'Enable Hook',
        javaClass: 'Java Class',
        method: 'Method',
        argsConfig: 'Arguments',
        importSuccess: 'Imported',
        basicName: 'API Name',
        basicTags: 'Tags',
        basicDesc: 'Description',
        basicUsage: 'Documentation',
        dragFile: 'Click or Drag to upload',
        authType: 'Auth Type',
        inheritOp: 'Inherit',
        customOp: 'Custom',
        none: 'None',
        commaMode: 'Comma Mode',
        colonMode: 'Colon Mode',
        batchFormatComma: 'Format: Key,Type,Required,Example,Description',
        batchFormatColon: 'Format: Key: Example',
        cancel: 'Cancel',
        confirm: 'Confirm',
        visualMode: 'Visual Mode',
        codeMode: 'Code Mode',
        sourcePath: 'Source Path',
        mockValue: 'Mock',
        addStatus: 'Add Status',
        rootNode: 'Root',
        addChild: 'Add Child',
        method: 'Method',
        apiPath: 'API Path',
        sendRequest: 'Send Request',
        genJwt: 'Generate JWT',
        oauth2Flow: 'OAuth2 Flow',
    }
};
